# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish to Gradle Plugin Portal on new Version tag

on:
  push:
    tags:        
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #        os: [ ubuntu-latest, windows-latest, macos-latest ] //Some day
        os: [ windows-latest, macos-latest ]
        java: [ 1.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{  matrix.java  }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{  matrix.java  }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info
      - name: Archive Test Report
        uses: actions/upload-artifact@v2
        with:
          name: gradle-test-report
          path: ./build/reports//tests/functionalTest/*
        if: ${{ failure() }}
    
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{  matrix.java  }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{  matrix.java  }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish new version to Gradle Plugins Portal
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
